WebApp/Models/ErrorViewModel.cs
namespace WebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApp/Controllers/BookController.cs
using BookServiceReference;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;

namespace WebApp.Controllers
{
    public class BookController : Controller
    {
        private readonly BookServiceClient bookService = new BookServiceClient();

        // GET: BookController
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public async Task<ActionResult> _TableBodyPartial(string search = "")
        {
            int idUser = this.GetUser();
            var books = await bookService.GetSearchAsync(search, idUser);
            return PartialView("_BookTableBodyPartial", books);
        }

        [Authorize]
        [HttpPost("Book/CreateReservation")]
        public async Task<ActionResult> CreateReservation(int idBook)
        {

            int idUser = this.GetUser();

            var body = new ReservationRequest
            {
                IdBook = idBook,
                IdUser = idUser,
            };

            var reservation = await bookService.CreateReservationAsync(body);

            if (reservation == null) return BadRequest(reservation);

            return Ok(reservation);
        }

        private int GetUser()
        {
            int idUser = Convert.ToInt32(User.FindFirstValue(JwtRegisteredClaimNames.Jti));

            return idUser;
        }
    }
}

WebApp/Controllers/EventController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class EventController : Controller
    {
        // GET: EventController
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return Redirect("Book/Index");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApp/Controllers/LoginController.cs
using BookServiceReference;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using UserServiceReference;

namespace WebApp.Controllers
{
    public class LoginController : Controller
    {
        private readonly UserServiceClient userService = new UserServiceClient();
        private IConfiguration _config;

        public LoginController(IConfiguration config)
        {
            _config = config;
        }


        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Authenticate(CredentialRequestDto credential)
        {
            var user = await userService.LoginAsync(credential);

            if (user == null) return Unauthorized(new { message = "Not authorized" });

            var securityKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_config["Jwt:Key"]));
            var credentials = new SigningCredentials(securityKey, SecurityAlgorithms.HmacSha256);

            var claims = new[]
			{
                new Claim(JwtRegisteredClaimNames.Name, user.FirstName),
                new Claim(JwtRegisteredClaimNames.Sub, user.LastName),
				new Claim(JwtRegisteredClaimNames.Email, user.Email),
                new Claim(JwtRegisteredClaimNames.Jti, user.IdUser.ToString())
			};

            var Sectoken = new JwtSecurityToken(_config["Jwt:Issuer"],
              _config["Jwt:Issuer"],
              claims,
              expires: DateTime.Now.AddDays(2),
              signingCredentials: credentials);

            var token = new JwtSecurityTokenHandler().WriteToken(Sectoken);

            return Ok(new
            {
                AccessToken = token,
                User = user,
            });
        }

        [Authorize]
        public ActionResult verifyToken()
        {
            var user = new UserResponseDto
            {
                IdUser = Convert.ToInt32(User.FindFirstValue(JwtRegisteredClaimNames.Jti)),
                FirstName = User.FindFirstValue(JwtRegisteredClaimNames.Name),
                LastName = User.FindFirstValue(ClaimTypes.NameIdentifier),
                Email = User.FindFirstValue(ClaimTypes.Email),
                Status = 1
            };

            return Ok(user);
        }
    }
}

WebApp/Views/Book/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Libros Page";
}

<style>
    .search {
        max-width: 350px;
    }
</style>

@section Scripts{
    <script src="~/js/books.js"></script>
}

<h1 class="fs-2 pb-3">Libros</h1>

<div class="d-flex justify-content-end gap-2 pb-5">
    <input id="input-search" class="form-control search" type="text" placeholder="Ingrese código o nombre del libro" aria-label="default input example">
    <button id="btn-search" type="button" class="btn btn-primary px-4">Buscar</button>
</div>

<table class="table table-hover" id="table-book">
    <thead>
        <tr>
            <th scope="col">Item</th>
            <th scope="col">Código</th>
            <th scope="col">Título</th>
            <th scope="col">Disponible</th>
            <th scope="col">Estado</th>
            <th scope="col">Fecha Reserva</th>
        </tr>
    </thead>
    <tbody id="table-body-book"></tbody>
</table>


<div class="modal none bg-black bg-opacity-50" id="modal-confirmation" tabindex="-1" aria-labelledby="exampleModalLiveLabel" aria-modal="true" role="dialog">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content border-0 p-4">
            <div class="pb-3">
                <h6 class="fs-3 text-center">¿Está seguro que desea reservar?</h6>
            </div>
            <div class="d-flex justify-content-evenly mx-5 mb-2">
                <button id="btn-modal-confirmation" type="button" class="btn btn-primary">ACEPTAR</button>
                <button id="btn-modal-cancelation" type="button" class="btn btn-danger">CANCELAR</button>
            </div>
        </div>
    </div>
</div>

<div class="modal none bg-black bg-opacity-50" id="modal-alert" tabindex="-1" aria-labelledby="exampleModalLiveLabel" aria-modal="true" role="dialog">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content border-0 p-4">
            <div class="pb-3">
                <h6 class="fs-3 text-center" id="title-modal-alert">¡Este libro ya esta reservado!</h6>
            </div>
            <div class="d-flex justify-content-center mb-2">
                <button id="btn-modal-alert" type="button" class="btn btn-primary">ACEPTAR</button>
            </div>
        </div>
    </div>
</div>

@* <div class="modal-backdrop fade show"></div> *@

WebApp/Views/Book/_BookTableBodyPartial.cshtml
@using BookServiceReference;

@model BookResponseDto[]

@if (Model != null)
{
    @foreach (BookResponseDto book in Model)
    {
        <tr class="tr-book @((bool)book.ReservedByMe! ? "table-info" : (bool)book.WaitReservedByMe! ? "table-warning" : "")">
            <th scope="row" class="th-book">
                @book.IdBook
                <input class="txt-idbook d-none" type="text" value="@book.IdBook" disabled="disabled" />
            </th>
            <td>@book.Code</td>
            <td class="td-title">@book.Title</td>
            <td>
                @* <svg bootstrap-icon="AlarmFill" width="24" height="24" aria-label="Alarms"></svg> *@
                @if ((bool)book.IsAvailable!)
                {
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-check-circle text-success" viewBox="0 0 16 16">
                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16" />
                        <path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05" />
                    </svg>
                }
                else
                {
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-x-circle text-danger" viewBox="0 0 16 16">
                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16" />
                        <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708" />
                    </svg>
                }
                <input class="check-available d-none" type="checkbox" checked="@book.IsAvailable" disabled="disabled" />
                <input class="check-reserved-me d-none" type="checkbox" checked="@book.ReservedByMe" disabled="disabled" />
                <input class="check-wait-reserved-me d-none" type="checkbox" checked="@book.WaitReservedByMe" disabled="disabled" />
            </td>
            <td class="td-book">
                @(@book.DateReservation == null ? "NO RESERVADO" : "RESERVADO")
                <input class="dtime-reservation d-none" type="datetime" value="@book.DateReservation" disabled="disabled" />
            </td>
            <td class="td-date-reservation">@book.DateReservation</td>
        </tr>
    }
}
else
{
    <tr>
        <td colspan="4" class="text-center text-danger">No hay registros</td>
    </tr>
}

WebApp/Views/Event/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Eventos Page";
}

<style>
    .search {
        max-width: 350px;
    }
</style>

@section Scripts{
    <script src="~/js/events.js"></script>
}

<h1 class="fs-2 pb-3">Eventos</h1>

<div class="d-flex justify-content-end gap-2 pb-5">
    <input id="input-search" class="form-control search" type="text" placeholder="Ingrese código o nombre del libro" aria-label="default input example">
    <button id="btn-search" type="button" class="btn btn-primary px-4">Buscar</button>
</div>

<table class="table" id="table-book">
    <thead>
        <tr>
            <th scope="col">Código</th>
            <th scope="col">Título</th>
            <th scope="col">Usuario</th>
            <th scope="col">Evento</th>
            <th scope="col">Fecha Registro</th>
        </tr>
    </thead>
    <tbody id="table-body-event"></tbody>
</table>

WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApp/Views/Login/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Login Page";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script src="~/js/login.js"></script>
}

<h1>Página de Eventos</h1>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">Login</div>
                <div class="card-body">
                    <form id="form-login">
                        <div class="form-group">
                            <label for="username">Correo</label>
                            <input type="email" class="form-control" id="Email" name="Email" placeholder="example@email.com" required>
                        </div>
                        <div class="form-group">
                            <label for="password">Contraseña</label>
                            <input type="password" class="form-control" id="Password" name="Password" required placeholder="••••••••">
                        </div>
                        <button type="submit" class="btn btn-primary">Iniciar sesión</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand fw-bold" asp-area="" asp-controller="Home" asp-action="Index">Reserva tu Libro</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Libros</a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Event" asp-action="Index">Eventos</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" id="link-angular" href="http://localhost:4200">Eventos y Reserva en espera (ANGULAR)</a>
                        </li>
                    </ul>
                    <span id="span-user" class="fw-bold d-inline-block me-4">Wilmer Reluz</span>
                    <button id="btn-logout-x" type="button" class="btn btn-danger">Cerrar Sesión</button>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Wilmer Reluz - 2023
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/_layout.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApp/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>